// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

import (
	"github.com/AlfredoPastor/ddd-go/purchasing/internal/config"
	"github.com/AlfredoPastor/ddd-go/purchasing/internal/order/application/creator"
	"github.com/AlfredoPastor/ddd-go/purchasing/internal/order/infraestructure/bus"
	"github.com/AlfredoPastor/ddd-go/purchasing/internal/order/infraestructure/httpController"
	"github.com/AlfredoPastor/ddd-go/purchasing/internal/order/infraestructure/store"
	"github.com/AlfredoPastor/ddd-go/shared/ginhttp"
	"github.com/AlfredoPastor/ddd-go/shared/mongoatlas"
	"github.com/AlfredoPastor/ddd-go/shared/rabbitmq"
)

// Injectors from wire.go:

func InitializeServer() (Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return Server{}, err
	}
	httpServer := ginhttp.NewHttpServer(configConfig)
	mongoClient, err := mongoatlas.NewMongoClient(configConfig)
	if err != nil {
		return Server{}, err
	}
	orderRepository := store.NewOrderRepository(mongoClient)
	rabbitClient := rabbitmq.NewRabbitClient(configConfig)
	busBus := bus.NewBus(rabbitClient)
	orderCreatorService := creator.NewOrderCreatorService(orderRepository, busBus)
	httpControllerHttpController := httpController.NewHttpController(httpServer, orderCreatorService)
	server := NewServer(httpControllerHttpController, busBus)
	return server, nil
}
