// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/AlfredoPastor/ddd-go/purchasing/internal/config"
	"github.com/AlfredoPastor/ddd-go/purchasing/internal/order/infraestructure/bus"
	"github.com/AlfredoPastor/ddd-go/shared/ginhttp"
	"github.com/AlfredoPastor/ddd-go/shared/rabbitmq"
)

// Injectors from wire.go:

func InitializeServer() (Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return Server{}, err
	}
	httpServer := ginhttp.NewHttpServer(configConfig)
	rabbitClient := rabbitmq.NewRabbitClient(configConfig)
	busBus := bus.NewBus(rabbitClient)
	server := NewServer(httpServer, busBus)
	return server, nil
}
